### ISSUE TITLE
release 0.1.1 doesn't define `conform/2` for contract

### ISSUE THREAD

**Issue by jvantuyl** [solnic/drops#34]
I get this warning when I compile with 0.1.1:
```
warning: function conform/2 required by behaviour Drops.Contract is not implemented (in module ModuleName)
  lib/module_name.ex:1: ModuleName (module)
```

Goes away with 0.1.0, presumably because that function is defined?

**Comment by solnic** [comment]
Ahh thank you for reporting this! I'll get this fixed in 0.2.0 :)
