### ISSUE TITLE
missing alias for type spec in Contract behaviour

### ISSUE THREAD

**Issue by jvantuyl** [solnic/drops#35]
When I run Dialyzer against code I've build with `Drops.Contract`, it gives warnings like this:
```
lib/module_name.ex:20:callback_arg_type_mismatch
The inferred type for the 2nd argument is not a
supertype of the expected type for the conform/3 callback
in the Drops.Contract behaviour.

Success type:
%Drops.Types.Map{_ => _}

Behaviour callback type:
Types.Map
```

It looks like we need to alias `Drops.Types` or fully specify the remote type in the callback spec.

**Comment by jvantuyl** [comment]
Or maybe this is this fixed on `main`?

**Comment by solnic** [comment]
Thanks for reporting. I'll revisit this once I'm done with Types-related rework in #36 :)

**Comment by solnic** [comment]
This specific warning is gone in main, so I'm going to close this.
