### ISSUE TITLE
Union data type

### ISSUE THREAD

**Issue by ilyabayel** [solnic/drops#37]
Hey, @solnic. How're you doing? Does this library support union types?

I would like to validate a map with union data type. Something like form with lots of `Node` where `Node = Field | Section`. We could think of it like:
```elixir
defmodule Field do
  ...
end

defmodule Section do
  ...
end

defmodule Node do
  @type t :: Field.t() | Section.t()
end
```

I see this `union` type describer as a function named `union` which accepts array of types.

```elixir
  union([float(), integer(), string()])
```

For my specific case I could use it like:

```elixir
defmodule FormContract do
  use Drops.Contract

  schema do
    %{
      required(:title) => string(:filled?),
      required(:nodes) =>
        list(
          union([
            %{
              required(:__type) => "Field",
              required(:name) => string(:filled?),
              required(:value) => union([integer(), float(), string(:filled?), boolean()])
            },
            %{
              required(:__type) => "Section",
              required(:name) => string(:filled?),
              required(:fields) =>
                list(%{
                  required(:__type) => "Field",
                  required(:name) => string(:filled?),
                  required(:value) => union([integer(), float(), string(:filled?), boolean()])
                })
            }
          ])
        )
    }
  end
end
```

With your new [Custom types](https://github.com/solnic/drops/pull/36) it will be way easier to read:

```elixir
defmodule FormContract do
  use Drops.Contract

  defmodule Field do
    use Drops.Type, %{
      required(:__type) => "Field",
      required(:name) => string(:filled?),
      required(:value) => union([integer(), float(), string(:filled?), boolean()])
    }
  end

  defmodule Section do
    use Drops.Type, %{
      required(:__type) => "Section",
      required(:name) => string(:filled?),
      required(:fields) => list(Field)
    }
  end

  # Node = Field | Section
  defmodule Node do
    use Drops.Type, union([Field, Section])
  end

  schema do
    %{
      required(:title) => string(:filled?),
      required(:nodes) => list(Node)
    }
  end
end
```

What do you think? I could try to implement it if you don't mind

**Comment by ilyabayel** [comment]
we could also implement [number type](https://github.com/solnic/drops/issues/33) as `union([float(), integer()])`

**Comment by solnic** [comment]
hey sorry I missed the notification about this issue! Yes, lemme first finish custom types PR and we can get back to your proposal :)

**Comment by solnic** [comment]
@ilyabayel hey there :) I'm more-or-less done with custom types. One thing I'd like to add is support for the syntax you showed here `use Drops.Type, %{...}` which defines a custom map type. This shouldn't be too difficult to do now.

Please let me know if you're still interested in adding `union` function. Also notice that there's `type` function which supports passing an array with types as it's first argument, but I think `union` will be better as it's more explicit. I guess we should also rename `Types.Sum` to `Types.Union`.
